# Project
version=0.12.2
group=net.chococraft

# Common
minecraft_version=1.21.4

# NeoForge
neo_version=21.4.141
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.119.3+1.21.4
fabric_loader_version=0.16.14
cloth_config_version=17.0.144
mod_menu_version=13.0.3

# Dependencies
architectury_version=15.0.3
jei_version=20.0.0.4
#patchouli_version=1.21-88
#patchouli_provider_version=1.21.1-1.0.11-Snapshot.5

# Mod options
mod_name=chococraft
mod_author=Mrbysco
mod_id=chococraft

#Publishing
curseforge_id=225280
modrinth_id=bPTEaC7v

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
