# Project
version=0.14.3
group=net.chococraft

# Common
minecraft_version=1.21.8

# NeoForge
neo_version=21.8.38
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Dependencies
architectury_version=17.0.8
jei_minecraft=1.21.8
jei_version=24.0.0.2
#patchouli_version=1.21-88
#patchouli_provider_version=1.21.1-1.0.11-Snapshot.5

# Mod options
mod_name=chococraft
mod_author=Mrbysco
mod_id=chococraft

#Publishing
curseforge_id=225280
modrinth_id=bPTEaC7v

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
