# Project
version=0.14.3
group=net.chococraft

# Common
minecraft_version=1.21.10

# NeoForge
neo_version=21.10.37-beta
neogradle.subsystems.parchment.minecraftVersion=1.21.10
neogradle.subsystems.parchment.mappingsVersion=2025.10.12
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.137.0+1.21.10
fabric_loader_version=0.17.3
cloth_config_version=20.0.148
mod_menu_version=16.0.0-rc.1

# Dependencies
architectury_version=18.0.6
jei_minecraft=1.21.10
jei_version=26.0.0.4
#patchouli_version=1.21-88
#patchouli_provider_version=1.21.1-1.0.11-Snapshot.5

# Mod options
mod_name=chococraft
mod_author=Mrbysco
mod_id=chococraft

#Publishing
curseforge_id=225280
modrinth_id=bPTEaC7v

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
